### ISSUE TITLE
Webui not fitting in screen

### ISSUE THREAD

**Issue by aroundmyroom** [l3uddz/sonarrAnnounced#6]
![image](https://cloud.githubusercontent.com/assets/250108/22264099/22bb6bba-e277-11e6-8e21-344c919a0b7d.png)

I have a small screen, the UI does not notice .

**Comment by l3uddz** [comment]
let me know if the last commit helps.

**Comment by aroundmyroom** [comment]
Will check it tonight, here in my office I have big screen .. ;-)

**Comment by aroundmyroom** [comment]
![image](https://cloud.githubusercontent.com/assets/250108/22301022/be0e22bc-e329-11e6-8cfa-b2ea66d3374d.png)

I think this is reasonable. Ok for me. thanks !

**Comment by l3uddz** [comment]
great.
