### ISSUE TITLE
HD-Torrents Support

### ISSUE THREAD

**Issue by acepilot1023** [l3uddz/sonarrAnnounced#9]
Would love if you could convert the tracker file for HD-Torrents. I know there is a lot of interest in this, seeing as we don't have an API.

Here is the tracker file: https://github.com/autodl-community/autodl-trackers/blob/master/HD-Torrents.tracker

Cheers!

**Comment by l3uddz** [comment]
I'll certainly take a look at adding hd-torrents, it looks like it requires a cookie instead of an authkey/torrentpass added to the torrent link, which could prove problematic, so it may require a little thinking / tinkering. Do you know if hd-torrents supports the authkey/torrentpass method?

**Comment by acepilot1023** [comment]
I have tried to get both the API and authkey methods implemented for other projects, to no avail. 

Hence the interest, we are shooting ourselves in the foot currently.

**Comment by l3uddz** [comment]
Ah I see. Well I will take a look at implementing it. If sonarr is capable of using a cookie with the release/push api endpoint it should be fairly easy to add. If it doesn't, I'll have to take a look at reimplementing the torrent server method I was originally using, for trackers such as this (sonarr would ask this script for the torrent, which would download it and serve it to sonarr). If your up for helping testing it would be helpful as would prove troublesome testing without being able to actually download torrent files.

**Comment by acepilot1023** [comment]
I'll setup a testing instance on my VPS

**Comment by l3uddz** [comment]
Ok great. I'll reply to this issue when I have began working on it and need some testing done. It's beneficial I think to do this because I'm sure there are other trackers out there that would need to be done this way too.
